version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: "Australia/Brisbane"
  open-pull-requests-limit: 10
  target-branch: develop