name: Manual Build Job

on: workflow_dispatch

jobs:
  initialize_and_build:
    name: Initialize repo and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Set up project
        run: |
          npm -g install yarn
          yarn install
          yarn clean

      - name: Build Public files
        run: yarn build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: Set up git credentials
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.name "$USER_NAME"
          git config --local user.email "$USER_EMAIL"

      - name: Deploy to GitHub Pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DEPLOY_BRANCH: master
        run: |
          # yarn deploy
          bash ./.github/workflows/build.bash